# Подготовка данных

In [1]:
import pandas as pd
import numpy as np

### загружаем данные

In [7]:
data_raw = pd.read_excel("test_DS.xlsx")

In [8]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4704 entries, 0 to 4703
Columns: 131 entries, id to feature 128
dtypes: float64(128), int64(3)
memory usage: 4.7 MB

In [9]:
data_raw.head()

,id,class,age,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,...,feature 119,feature 120,feature 121,feature 122,feature 123,feature 124,feature 125,feature 126,feature 127,feature 128
0,1,0,13,0.506822,0.572237,0.563280,0.564596,0.673946,1.000000,0.639703,...,0.659633,0.554634,0.606054,0.535127,0.592213,0.646772,0.578132,0.409359,0.617043,0.684861
1,2,0,13,0.634540,0.656879,0.661679,0.514073,0.597017,0.653414,0.613749,...,0.592704,0.809567,0.652914,0.492657,0.634188,0.966302,0.713014,0.484816,0.665300,0.641281
2,3,1,13,0.500905,0.645632,0.651043,0.529001,0.658857,0.803911,0.684024,...,0.574472,0.570743,0.729069,0.491912,0.668273,0.694074,0.594661,0.509790,0.687504,0.643744
3,4,0,13,0.493149,0.599626,0.761525,0.569928,0.550057,0.724291,0.546091,...,0.602609,0.589338,0.736556,0.585193,0.730247,0.712183,0.630339,0.633105,0.753155,0.463349
4,5,0,13,0.520421,0.664441,0.572142,0.555681,0.627189,0.633925,0.546091,...,0.602609,0.602220,0.637908,0.554012,0.588330,0.745618,0.560864,0.475226,0.590734,0.642919

### Перемешиваем данные

In [10]:
data = data_raw.sample(frac=1).reset_index(drop=True)

In [11]:
data.head()

,id,class,age,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,...,feature 119,feature 120,feature 121,feature 122,feature 123,feature 124,feature 125,feature 126,feature 127,feature 128
0,2614,0,30,0.453811,0.479206,0.591519,0.759556,0.623861,0.619786,0.589054,...,0.523850,0.489500,0.577616,0.487076,0.532485,0.752460,0.720255,0.451843,0.571559,0.671240
1,1645,1,25,0.775899,0.832611,0.654497,0.543012,0.649499,0.609313,0.690712,...,0.560812,0.681025,0.771437,0.617585,0.780181,0.881057,0.679409,0.440373,0.645294,0.505496
2,1600,0,24,0.807016,0.702239,0.766729,0.575019,0.850083,0.690842,0.690145,...,0.612835,0.659846,0.814603,0.551337,0.814592,0.789458,0.720255,0.709303,0.632729,0.475133
3,2061,0,27,0.684190,0.687694,0.783678,0.660015,0.638006,0.591998,0.668957,...,0.555306,0.681770,0.729796,0.602220,0.720641,0.764360,0.713014,0.810325,0.719410,0.686242
4,3306,1,33,0.545436,0.552972,0.523495,0.413136,0.455855,0.504153,0.493043,...,0.470007,0.462026,0.594933,0.456684,0.628543,0.624664,0.586778,0.376835,0.587137,0.331834

### Разделяем на входной и выходной вектора

In [34]:
_id = data["id"]
_id.head()

0    2614
1    1645
2    1600
3    2061
4    3306
Name: id, dtype: int64

In [35]:
_class = data["class"]
_class.head()

0    0
1    1
2    0
3    0
4    1
Name: class, dtype: int64

In [36]:
_age = data["age"]
_age.head()

0    30
1    25
2    24
3    27
4    33
Name: age, dtype: int64

In [37]:
X = data.drop(columns=["id", "class", "age"])
X.head()

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 119,feature 120,feature 121,feature 122,feature 123,feature 124,feature 125,feature 126,feature 127,feature 128
0,0.453811,0.479206,0.591519,0.759556,0.623861,0.619786,0.589054,0.480861,0.570985,0.544365,...,0.523850,0.489500,0.577616,0.487076,0.532485,0.752460,0.720255,0.451843,0.571559,0.671240
1,0.775899,0.832611,0.654497,0.543012,0.649499,0.609313,0.690712,0.668142,0.666004,0.607825,...,0.560812,0.681025,0.771437,0.617585,0.780181,0.881057,0.679409,0.440373,0.645294,0.505496
2,0.807016,0.702239,0.766729,0.575019,0.850083,0.690842,0.690145,0.652982,0.715109,0.732593,...,0.612835,0.659846,0.814603,0.551337,0.814592,0.789458,0.720255,0.709303,0.632729,0.475133
3,0.684190,0.687694,0.783678,0.660015,0.638006,0.591998,0.668957,0.680517,0.625889,0.851675,...,0.555306,0.681770,0.729796,0.602220,0.720641,0.764360,0.713014,0.810325,0.719410,0.686242
4,0.545436,0.552972,0.523495,0.413136,0.455855,0.504153,0.493043,0.366889,0.389249,0.633766,...,0.470007,0.462026,0.594933,0.456684,0.628543,0.624664,0.586778,0.376835,0.587137,0.331834

### Разделяем на тестовую и учебную выборки

In [38]:
test_size = int(X.shape[0]*0.1)
test_index = list(X.index[0:test_size])
len(test_index)

470

In [39]:
train_id    = _id.drop(test_index)
train_class = _class.drop(test_index)
train_age   = _age.drop(test_index)
train_X     = X.drop(test_index)
train_X.head()

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 119,feature 120,feature 121,feature 122,feature 123,feature 124,feature 125,feature 126,feature 127,feature 128
470,0.603388,0.634696,0.626717,0.558324,0.654578,0.575049,0.600980,0.582501,0.561031,0.784197,...,0.562962,0.636833,0.627870,0.484762,0.618690,0.840170,0.626934,0.574317,0.630160,0.691683
471,0.528087,0.614069,0.563280,0.543012,0.575354,0.522518,0.582794,0.668142,0.518577,0.580717,...,0.603434,0.480122,0.495261,0.597696,0.463836,0.680829,0.575518,0.523153,0.687504,0.454245
472,0.746276,0.711580,0.770736,0.561386,0.724866,1.000000,0.612610,0.547153,0.660158,0.732593,...,0.602609,0.577407,0.814603,0.483342,0.814592,0.812342,0.588372,0.515145,0.660319,0.649059
473,0.570767,0.657780,0.651964,0.669270,0.697433,0.675411,0.695070,0.593877,0.599409,0.572940,...,0.659633,0.804933,0.876524,0.602220,0.841652,0.966302,0.640209,0.679317,0.614431,0.626926
474,0.746276,0.560858,0.559560,0.459482,0.633723,0.556132,0.476458,0.538505,0.546867,0.540594,...,0.706766,0.497423,0.639574,0.489462,0.600116,0.651256,0.565179,0.697452,0.653779,0.424980

In [45]:
test_id    = _id.loc[test_index]
test_class = _class.loc[test_index]
test_age   = _age.loc[test_index]
test_X     = X.loc[test_index]
test_X.head()

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 119,feature 120,feature 121,feature 122,feature 123,feature 124,feature 125,feature 126,feature 127,feature 128
0,0.453811,0.479206,0.591519,0.759556,0.623861,0.619786,0.589054,0.480861,0.570985,0.544365,...,0.523850,0.489500,0.577616,0.487076,0.532485,0.752460,0.720255,0.451843,0.571559,0.671240
1,0.775899,0.832611,0.654497,0.543012,0.649499,0.609313,0.690712,0.668142,0.666004,0.607825,...,0.560812,0.681025,0.771437,0.617585,0.780181,0.881057,0.679409,0.440373,0.645294,0.505496
2,0.807016,0.702239,0.766729,0.575019,0.850083,0.690842,0.690145,0.652982,0.715109,0.732593,...,0.612835,0.659846,0.814603,0.551337,0.814592,0.789458,0.720255,0.709303,0.632729,0.475133
3,0.684190,0.687694,0.783678,0.660015,0.638006,0.591998,0.668957,0.680517,0.625889,0.851675,...,0.555306,0.681770,0.729796,0.602220,0.720641,0.764360,0.713014,0.810325,0.719410,0.686242
4,0.545436,0.552972,0.523495,0.413136,0.455855,0.504153,0.493043,0.366889,0.389249,0.633766,...,0.470007,0.462026,0.594933,0.456684,0.628543,0.624664,0.586778,0.376835,0.587137,0.331834

In [46]:
test_class

0      0
1      1
2      0
3      0
4      1
      ..
465    0
466    0
467    1
468    1
469    1
Name: class, Length: 470, dtype: int64

# Нормируем входной вектор

In [100]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer

In [50]:
X_scaler = StandardScaler()
X_scaler.fit(train_X)
train_X_scaled = pd.DataFrame(X_scaler.transform(train_X))
test_X_scaled  = pd.DataFrame(X_scaler.transform(test_X))

In [51]:
train_X_scaled.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,127
0,-0.091613,0.138491,-0.113967,0.234237,0.238714,-0.436708,0.086031,0.481227,-0.549777,1.515784,...,-0.071041,0.124445,-0.309087,-0.836597,-0.132367,0.829552,0.274995,0.405268,0.045786,1.285866
1,-0.561351,-0.081905,-0.627856,0.061421,-0.762623,-0.837125,-0.135423,1.377345,-0.929067,-0.153963,...,0.354637,-1.227607,-1.315760,0.737968,-1.292440,-0.780922,-0.360619,-0.024276,0.893844,-0.625618
2,0.799753,0.959963,1.052702,0.268801,1.127114,2.802464,0.227651,0.111357,0.335829,1.092320,...,0.345956,-0.388267,1.108445,-0.856389,1.335222,0.548289,-0.201715,-0.091511,0.491809,0.942721
3,-0.295107,0.385131,0.090554,1.486393,0.780370,0.328293,1.231756,0.600256,-0.206906,-0.217784,...,0.945730,1.574754,1.578507,0.801054,1.537933,2.104379,0.439100,1.286784,-0.186819,0.764539
4,0.799753,-0.650436,-0.657996,-0.881314,-0.024875,-0.580907,-1.430271,0.020862,-0.676324,-0.483211,...,1.441472,-1.078342,-0.220244,-0.771065,-0.271513,-1.079812,-0.488433,1.439035,0.395084,-0.861215

In [52]:
test_X_scaled.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,127
0,-1.024703,-1.522843,-0.399101,2.505375,-0.149530,-0.095704,-0.059199,-0.582300,-0.460855,-0.452269,...,-0.482418,-1.146696,-0.690585,-0.804324,-0.778165,-0.056943,1.428637,-0.622959,-0.820847,1.121289
1,0.984549,2.253120,0.111076,0.061421,0.174517,-0.175530,1.178691,1.377345,0.388067,0.068479,...,-0.093652,0.505711,0.780766,1.015278,1.077430,1.242793,0.923700,-0.719253,0.269603,-0.213027
2,1.178658,0.860151,1.020247,0.422661,2.709765,0.445916,1.171786,1.218712,0.826769,1.092320,...,0.453512,0.322992,1.108445,0.091621,1.335222,0.317003,1.428637,1.538533,0.083790,-0.457463
3,0.412448,0.704750,1.157547,1.381941,0.029254,-0.307515,0.913783,1.506826,0.029667,2.069506,...,-0.151565,0.512143,0.464656,0.801054,0.631391,0.063331,1.339122,2.386655,1.365689,1.242062
4,-0.453126,-0.734689,-0.950150,-1.404386,-2.273006,-0.977108,-1.228311,-1.774858,-2.084505,0.281354,...,-1.048732,-1.383735,-0.559124,-1.228070,-0.058551,-1.348583,-0.221430,-1.252678,-0.590459,-1.611087

# Определение класса с помощью градиентного бустинга

In [88]:
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier

In [94]:
gbc = GradientBoostingClassifier()
gbc.fit(train_X_scaled, train_class)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [95]:
predicted_class = gbc.predict(test_X_scaled)

In [107]:
list(zip(test_class, predicted_class))

[(0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1)]

In [108]:
success = 0
for p, t in zip(predicted_class, test_class):
    if p == t:
        success += 1
success / len(test_class)

0.8851063829787233

Спрогнозировано с точностью 88%

# Определение возраста с помощью градиентного бустинга

In [109]:
from sklearn.ensemble import GradientBoostingRegressor

In [110]:
gbr = GradientBoostingRegressor()
gbr.fit(train_X_scaled, train_age)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [111]:
predicted_age = gbr.predict(test_X_scaled)

In [112]:
list(zip(test_age, predicted_age))

[(30, 30.143447192707214),
 (25, 32.05668324995753),
 (24, 28.363902771776427),
 (27, 32.31793267241814),
 (33, 32.508597260911344),
 (20, 27.083658281707404),
 (18, 16.76107471706104),
 (27, 34.552719805530685),
 (36, 34.12881332812436),
 (27, 34.153712911655305),
 (18, 22.089629830644927),
 (40, 34.42104636783958),
 (25, 29.7162736495071),
 (27, 35.941006843435964),
 (25, 30.399892829224875),
 (17, 17.50882856460776),
 (16, 16.778103736616824),
 (48, 30.086568037720976),
 (33, 34.06921569133399),
 (29, 32.80925823409192),
 (33, 35.33314860589886),
 (25, 27.173322940481114),
 (20, 20.770758805157442),
 (30, 37.932637772051976),
 (19, 20.89219754376629),
 (38, 32.55005746057927),
 (33, 30.379718118881197),
 (30, 39.75969643701723),
 (30, 33.31867932451895),
 (36, 35.826369995567234),
 (44, 36.54690595161397),
 (15, 18.301017578894374),
 (19, 14.990840168400185),
 (36, 32.53610381462162),
 (27, 30.351905590821993),
 (20, 20.227284492081708),
 (25, 28.06506202311132),
 (35, 21.203576402640792),
 (32, 35.00586204288708),
 (29, 30.157753644088075),
 (29, 29.790188709593806),
 (47, 37.732489537382506),
 (35, 34.365979390867466),
 (20, 13.812802829841619),
 (29, 27.94164093989854),
 (45, 28.746639501979985),
 (15, 11.976746920439162),
 (20, 19.729471971355096),
 (15, 16.03374482756766),
 (27, 30.995328558429293),
 (17, 19.51737718710166),
 (25, 33.19212050476661),
 (30, 31.64504620271937),
 (59, 32.4542778505334),
 (16, 17.118436379254472),
 (21, 25.70321426620487),
 (17, 16.420066565554798),
 (49, 37.05629218674783),
 (25, 29.202947268129215),
 (33, 33.79767527575614),
 (48, 38.554868684652284),
 (16, 18.993262000328404),
 (49, 40.07515632005329),
 (40, 33.384495569739094),
 (18, 19.291767468427),
 (15, 26.61972951379755),
 (22, 28.627227415815618),
 (15, 23.027547812113355),
 (31, 28.83927379248717),
 (20, 27.921713023135847),
 (25, 27.002236093378336),
 (21, 23.229718117471393),
 (30, 29.98396581158486),
 (23, 18.73827445803755),
 (40, 31.701705152228346),
 (36, 34.461228033062994),
 (37, 35.72648073368847),
 (33, 33.34142717776112),
 (19, 22.421472640619804),
 (39, 34.420691605504146),
 (27, 27.262446144025468),
 (38, 35.80501791160402),
 (39, 24.506340810623392),
 (25, 29.43865973780167),
 (17, 15.683328749016235),
 (33, 32.39880595769127),
 (18, 34.728929260901374),
 (22, 25.528043871408155),
 (24, 18.801428120561486),
 (14, 16.82187040393722),
 (19, 28.70764477964673),
 (33, 26.46985462883983),
 (36, 35.10688841065323),
 (30, 29.972346289916874),
 (40, 35.61028256183277),
 (21, 30.26919435532268),
 (32, 34.69321359562354),
 (15, 15.510361068372962),
 (33, 30.388243671863925),
 (43, 33.231652733405035),
 (15, 21.582725117056505),
 (27, 31.26677065778841),
 (52, 18.695939214985174),
 (33, 32.49460621849141),
 (22, 18.488662882000703),
 (19, 16.552628246275336),
 (25, 22.1907415079501),
 (25, 34.286252436792545),
 (33, 31.112771118256813),
 (35, 30.893934896747428),
 (32, 39.6296036250136),
 (25, 30.24400248040617),
 (38, 33.15128669126759),
 (30, 40.01239561356632),
 (19, 19.691670572801957),
 (17, 21.016565042516223),
 (30, 31.460315159648655),
 (37, 36.4295873535274),
 (55, 37.68076169824836),
 (27, 32.225541998563095),
 (39, 31.689690895645807),
 (15, 20.408253716438868),
 (22, 28.1076272025698),
 (14, 15.804293497541146),
 (15, 25.198618431229924),
 (21, 13.728712320701018),
 (19, 34.70234260707629),
 (50, 32.70378429180282),
 (16, 18.964261177227094),
 (16, 23.40991235947381),
 (28, 22.330808290465928),
 (27, 32.08390953332235),
 (29, 33.59655776011896),
 (25, 31.328603277954155),
 (29, 32.554438030760025),
 (33, 32.28540691912151),
 (30, 33.73206700225988),
 (38, 37.21273408600236),
 (36, 33.49942042877129),
 (24, 17.540222927108175),
 (29, 31.8196779108866),
 (31, 29.506898063899296),
 (16, 23.304209704840705),
 (29, 35.5616748883819),
 (30, 34.726480640511625),
 (41, 39.200428568071835),
 (18, 25.240420225820646),
 (20, 22.429890932366497),
 (30, 31.891798200699675),
 (32, 32.222089342106244),
 (31, 32.693530408241024),
 (15, 23.69435977379659),
 (37, 33.9670486746808),
 (36, 32.03057834684509),
 (48, 35.3062037572539),
 (32, 31.361235976724604),
 (30, 35.006268121991745),
 (45, 33.40957949400138),
 (16, 18.221592256654464),
 (27, 32.004801871162854),
 (35, 33.20398072834278),
 (20, 30.56738188119858),
 (29, 35.70078773951759),
 (14, 28.36647835387601),
 (39, 37.92641656030838),
 (32, 31.149901526875688),
 (30, 30.041651550841454),
 (21, 25.102567742158676),
 (18, 20.727980125994563),
 (20, 23.6628470846686),
 (43, 34.32938294222872),
 (41, 38.14806698468293),
 (14, 22.705663143823955),
 (36, 32.39645770544261),
 (23, 27.501049060566093),
 (25, 30.340524349266648),
 (27, 28.667194312766178),
 (33, 35.021381151293554),
 (39, 36.57996987400295),
 (27, 36.65371146754463),
 (33, 35.17988539716598),
 (19, 14.781571541739154),
 (25, 20.506428660599823),
 (27, 31.302879743797682),
 (48, 44.19126463461364),
 (36, 33.057882940371506),
 (15, 17.730027189752555),
 (14, 17.444313371089965),
 (35, 37.282532564471985),
 (17, 14.680089701503485),
 (45, 34.63885487445169),
 (33, 35.00234736926125),
 (20, 29.482940498314655),
 (38, 27.396588655340903),
 (28, 33.85376435507183),
 (23, 21.96629621721488),
 (31, 31.209700941062774),
 (49, 37.29997753810406),
 (38, 35.03984455185042),
 (19, 19.255071794556144),
 (46, 40.093379423746406),
 (30, 27.313860100402245),
 (22, 20.44265506217412),
 (38, 35.398067049931655),
 (33, 35.07219867803322),
 (17, 17.2522499319332),
 (19, 20.362868704524622),
 (23, 22.45121820909497),
 (36, 33.620025904695545),
 (17, 19.15391665721834),
 (25, 35.07142978187977),
 (53, 40.543484195554605),
 (33, 34.7324821867057),
 (14, 22.565343358505192),
 (33, 25.65086274964716),
 (27, 28.470910643357936),
 (16, 18.41648298949349),
 (16, 16.93738215307599),
 (15, 17.591694442791354),
 (31, 39.62594352809546),
 (47, 36.97895607520037),
 (19, 19.99058780326267),
 (17, 20.56613964866383),
 (30, 29.164194847463452),
 (31, 33.613227696914784),
 (18, 18.177157338442484),
 (19, 17.33067856512715),
 (21, 21.639063638165155),
 (33, 32.3918643901622),
 (22, 26.562449137784924),
 (49, 33.70125954877693),
 (25, 27.702146608315083),
 (14, 16.832421428935387),
 (30, 35.13168686954493),
 (36, 33.49561895253962),
 (25, 29.636026785325836),
 (33, 31.095902312215696),
 (27, 30.670092169561073),
 (25, 21.957173112802707),
 (18, 30.333161027467796),
 (36, 31.926130158392606),
 (33, 33.390132402849396),
 (22, 21.435379462277375),
 (49, 37.0435826756997),
 (46, 32.49416886899646),
 (27, 32.9329248621728),
 (41, 35.123203600586564),
 (31, 30.776747580265237),
 (16, 18.81369747007986),
 (35, 40.3862175993358),
 (14, 20.845413689117535),
 (17, 15.800434969555452),
 (33, 35.72007464268249),
 (27, 25.36266071301135),
 (15, 25.31829421410006),
 (15, 19.933710897718687),
 (18, 19.232716228753837),
 (21, 30.53654320328239),
 (31, 29.824951510545034),
 (22, 30.417482697299064),
 (20, 15.84168427730642),
 (48, 32.56985383187393),
 (30, 32.05090078579435),
 (30, 31.250073986027864),
 (18, 21.50124912441098),
 (25, 27.98962431388015),
 (36, 41.82595362582778),
 (41, 30.357544286343952),
 (36, 31.830867360846597),
 (41, 35.56527390737033),
 (23, 22.177158993781287),
 (21, 20.00048284134526),
 (20, 18.90981538334303),
 (50, 32.70378429180282),
 (16, 17.130292061401537),
 (16, 23.299526349106344),
 (27, 31.163231679312624),
 (42, 38.31900927885179),
 (30, 32.382910111461534),
 (40, 29.37910242571514),
 (45, 39.25340470272572),
 (45, 34.442543206411514),
 (15, 28.981159692093957),
 (15, 25.638472829339975),
 (15, 18.330230930825767),
 (15, 14.90717973621505),
 (19, 17.258904565456458),
 (22, 26.637052969810608),
 (50, 34.97300558455359),
 (29, 32.08066125752449),
 (18, 14.284157530017602),
 (33, 36.0988833170384),
 (50, 35.24187051362825),
 (38, 36.20499136702281),
 (20, 26.57602461162492),
 (47, 38.10416140546261),
 (37, 30.69384911481751),
 (18, 26.432348463846374),
 (17, 19.495632618206763),
 (36, 28.579661077562),
 (37, 30.70038745746937),
 (16, 19.556572995292075),
 (19, 21.739272281246745),
 (36, 35.61355735042347),
 (31, 34.68045718727096),
 (36, 39.30325913576915),
 (15, 18.1945301098401),
 (40, 35.20650632172424),
 (27, 29.141313488054756),
 (39, 25.872615429971063),
 (30, 24.800465400886278),
 (16, 18.167332223796016),
 (15, 17.16102189004149),
 (14, 26.326801965302195),
 (31, 34.707405408295934),
 (31, 32.38645749522026),
 (37, 37.78736093657825),
 (27, 31.51801744135826),
 (14, 30.014338706238252),
 (50, 38.12772776260829),
 (31, 34.410885441318754),
 (37, 34.05158300163442),
 (38, 33.94810508609035),
 (33, 36.59079504735092),
 (49, 34.85023225496898),
 (37, 22.561689823675685),
 (17, 15.92174483429904),
 (58, 36.56175405709703),
 (41, 39.026071010834116),
 (41, 37.61771522428015),
 (28, 31.428192400552593),
 (32, 36.3345118409438),
 (14, 18.062729931705903),
 (18, 22.441915006862203),
 (40, 36.86042196250695),
 (47, 32.80627538496015),
 (20, 25.67591813930879),
 (19, 20.048617129806722),
 (30, 33.169138883077665),
 (19, 19.616009601122716),
 (25, 29.44676645994951),
 (21, 30.427107004474806),
 (21, 26.013744863731688),
 (14, 21.376895156339316),
 (15, 18.980447348966997),
 (17, 24.37512708883558),
 (32, 30.844054606645795),
 (29, 29.960877374744502),
 (37, 34.27410214485582),
 (44, 38.92972607289204),
 (21, 24.01818428186814),
 (18, 20.5876017897637),
 (33, 37.11241373507235),
 (27, 33.530971470321916),
 (37, 35.49374652221297),
 (16, 16.419212358861454),
 (25, 32.36264344162392),
 (25, 28.546388082106223),
 (29, 29.527681936082292),
 (30, 35.02011871875554),
 (32, 40.15148387127459),
 (31, 36.02370561169934),
 (30, 29.56465333750447),
 (19, 20.744868512705256),
 (38, 29.841208045914232),
 (49, 36.01913643453643),
 (21, 19.700650846672048),
 (33, 35.10881378554306),
 (30, 37.23153899579195),
 (25, 31.6656770920331),
 (47, 29.77052455268141),
 (14, 13.711694209784113),
 (27, 30.439130566991793),
 (50, 33.0854360173122),
 (25, 19.779232747172223),
 (19, 13.443786049963581),
 (31, 24.432774499641525),
 (20, 23.147360693550134),
 (19, 30.570622622286717),
 (33, 34.402203148693346),
 (30, 31.26198006809959),
 (38, 34.449737648328316),
 (30, 30.315875532607),
 (15, 12.837651704888115),
 (48, 33.578065915916646),
 (15, 22.384866042875156),
 (41, 35.100154243672726),
 (16, 18.05127648631687),
 (27, 34.05651015495786),
 (17, 18.416208237890203),
 (29, 39.639866784139706),
 (30, 29.280306175293013),
 (16, 16.912288975074862),
 (37, 39.29848126776787),
 (45, 36.038149329712866),
 (33, 27.417363426833873),
 (24, 29.805032841747167),
 (15, 23.905323680486312),
 (29, 27.202379001917308),
 (20, 15.785866961633712),
 (33, 37.865483238186826),
 (17, 19.42943669280307),
 (27, 33.017092650541635),
 (50, 41.59645572052828),
 (29, 35.486782397017315),
 (15, 19.398706507079908),
 (16, 21.24951899117186),
 (29, 33.95903657575549),
 (38, 37.47345840095093),
 (47, 35.43235805878865),
 (44, 37.260079180123974),
 (14, 19.14928940213914),
 (32, 33.95390865489289),
 (25, 33.01901988262323),
 (19, 23.143785788401942),
 (27, 31.696209545825603),
 (58, 41.3063415905412),
 (17, 23.25985634664103),
 (48, 45.41470524373747),
 (19, 28.28070609879152),
 (47, 36.11978983983552),
 (19, 19.2520059624847),
 (25, 35.714796753189546),
 (27, 35.27145051834164),
 (15, 16.019479382765926),
 (15, 16.726325224683684),
 (47, 32.40625123853402),
 (45, 34.65356324646154),
 (31, 30.854462915942477),
 (14, 16.42679342569284),
 (30, 29.900745956976746),
 (30, 33.15211042817726),
 (33, 31.945688006519344),
 (14, 20.214195063680737),
 (24, 15.43568428347744),
 (38, 34.74007232826483),
 (38, 30.711431654288507),
 (27, 22.792536385220142),
 (27, 22.01237104947819),
 (25, 31.387548103023615),
 (39, 32.82508178560084),
 (29, 27.74598138568607),
 (33, 38.61961280806316),
 (45, 31.551920474235846),
 (19, 27.34165190647222),
 (30, 30.918159883148395),
 (33, 29.287851608520047),
 (25, 20.333988747672926),
 (39, 29.977102398549828),
 (16, 22.22053979501157),
 (33, 28.779603560667983),
 (33, 35.92185100730988),
 (48, 30.806819015475284),
 (17, 13.281602179750147),
 (38, 33.49957680487675),
 (33, 20.315760745251964),
 (48, 37.402575484066915),
 (27, 33.013010575744055),
 (27, 34.98671483975937),
 (40, 35.71712419842323),
 (25, 36.59958953869304),
 (27, 36.6543845458467),
 (30, 30.405713494612275),
 (40, 31.16694256614746),
 (38, 32.53423882314953),
 (21, 29.116089810541414),
 (32, 31.694195221419577),
 (39, 36.2916385175302),
 (30, 23.0914047641493),
 (27, 31.211777727286165)]

In [114]:
error = 0
for p, t in zip(predicted_age, test_age):
    error += abs(p-t) / max(test_age)
success = 1 - error / len(test_age)
success

0.9126346504191469

Спрогнозировано с точностью 91%